'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PASS {0}.
        '''</summary>
        Friend ReadOnly Property FTPSocketSendPass() As String
            Get
                Return ResourceManager.GetString("FTPSocketSendPass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to QUIT.
        '''</summary>
        Friend ReadOnly Property FTPSocketSendQuit() As String
            Get
                Return ResourceManager.GetString("FTPSocketSendQuit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to USER {0}.
        '''</summary>
        Friend ReadOnly Property FTPSocketSendUser() As String
            Get
                Return ResourceManager.GetString("FTPSocketSendUser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to VolumeSerialNumber.
        '''</summary>
        Friend ReadOnly Property SysInfoHDDPropName() As String
            Get
                Return ResourceManager.GetString("SysInfoHDDPropName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to win32_logicaldisk.deviceid=&quot;&quot;{0}:&quot;&quot;.
        '''</summary>
        Friend ReadOnly Property SysInfoHDDQueryName() As String
            Get
                Return ResourceManager.GetString("SysInfoHDDQueryName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IPEnabled.
        '''</summary>
        Friend ReadOnly Property SysInfoMACIPName() As String
            Get
                Return ResourceManager.GetString("SysInfoMACIPName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MacAddress.
        '''</summary>
        Friend ReadOnly Property SysInfoMACPropName() As String
            Get
                Return ResourceManager.GetString("SysInfoMACPropName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Win32_NetworkAdapterConfiguration.
        '''</summary>
        Friend ReadOnly Property SysInfoMACQueryName() As String
            Get
                Return ResourceManager.GetString("SysInfoMACQueryName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SerialNumber.
        '''</summary>
        Friend ReadOnly Property SysInfoMoboPropName() As String
            Get
                Return ResourceManager.GetString("SysInfoMoboPropName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Win32_BaseBoard.
        '''</summary>
        Friend ReadOnly Property SysInfoMoboQueryName() As String
            Get
                Return ResourceManager.GetString("SysInfoMoboQueryName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to processorId.
        '''</summary>
        Friend ReadOnly Property SysInfoProcPropName() As String
            Get
                Return ResourceManager.GetString("SysInfoProcPropName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Win32_processor.
        '''</summary>
        Friend ReadOnly Property SysInfoProcQueryName() As String
            Get
                Return ResourceManager.GetString("SysInfoProcQueryName", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
