'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18408
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("NuSoft.NUI.Win.Forms.Modules.NuSoft001.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property account_balances_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("account_balances_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property account_balances_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("account_balances_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property cellsautoheight__16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cellsautoheight-_16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property cellsautoheight__32x32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cellsautoheight-_32x32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [A].
        '''</summary>
        Public ReadOnly Property FormatAkun() As String
            Get
                Return ResourceManager.GetString("FormatAkun", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [M0].
        '''</summary>
        Public ReadOnly Property FormatBulan0() As String
            Get
                Return ResourceManager.GetString("FormatBulan0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [Mr].
        '''</summary>
        Public ReadOnly Property FormatBulanR() As String
            Get
                Return ResourceManager.GetString("FormatBulanR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [R].
        '''</summary>
        Public ReadOnly Property FormatRegional() As String
            Get
                Return ResourceManager.GetString("FormatRegional", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [S].
        '''</summary>
        Public ReadOnly Property FormatSumber() As String
            Get
                Return ResourceManager.GetString("FormatSumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [Y2].
        '''</summary>
        Public ReadOnly Property FormatTahun2() As String
            Get
                Return ResourceManager.GetString("FormatTahun2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [Y4].
        '''</summary>
        Public ReadOnly Property FormatTahun4() As String
            Get
                Return ResourceManager.GetString("FormatTahun4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to select f02_getbeginningbalance({0},&apos;{1}&apos;).
        '''</summary>
        Public ReadOnly Property FunctionBeginningBalance() As String
            Get
                Return ResourceManager.GetString("FunctionBeginningBalance", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to select f02_getbeginningbalanceX({0},&apos;{1}&apos;).
        '''</summary>
        Public ReadOnly Property FunctionBeginningBalanceX() As String
            Get
                Return ResourceManager.GetString("FunctionBeginningBalanceX", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ada beberapa item yang tidak dapat dihapus, karena berasal dari modul lain..
        '''</summary>
        Public ReadOnly Property GLDeletedModul() As String
            Get
                Return ResourceManager.GetString("GLDeletedModul", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Jika ingin menghapus transaksi ini, harus dari modul yang bersangkutan..
        '''</summary>
        Public ReadOnly Property GLDeletedModulSolution() As String
            Get
                Return ResourceManager.GetString("GLDeletedModulSolution", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ada beberapa item yang tidak dapat dihapus, karena periode yang bersangkutan sudah ditutup..
        '''</summary>
        Public ReadOnly Property GLDeletedPeriode() As String
            Get
                Return ResourceManager.GetString("GLDeletedPeriode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Jika ingin menghapus transaksi ini, hubungi akunting anda untuk membuka periode yang bersangkutan..
        '''</summary>
        Public ReadOnly Property GLDeletedPeriodeSolution() As String
            Get
                Return ResourceManager.GetString("GLDeletedPeriodeSolution", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to select p_id,u_code,d_contact,d_date 
        '''from m01cmaingl
        '''where f_source in (2,4)
        '''and d_type=1
        '''and not p_id in (select fk_cashadvance from m01cmaingl where not fk_cashadvance is null).
        '''</summary>
        Public ReadOnly Property SQLCARemain() As String
            Get
                Return ResourceManager.GetString("SQLCARemain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to select p_id,u_code,d_contact,d_date 
        '''from m01cmaingl
        '''where f_source in (2,4)
        '''and d_type=1
        '''and (not p_id in (select fk_cashadvance from m01cmaingl where not fk_cashadvance is null) or p_id ={0}).
        '''</summary>
        Public ReadOnly Property SQLCARemainEdit() As String
            Get
                Return ResourceManager.GetString("SQLCARemainEdit", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
