'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to select f03_getbeginningbalancewithcurrentpayment({0},{1}).
        '''</summary>
        Friend ReadOnly Property SP03SaldoAwalBergerak() As String
            Get
                Return ResourceManager.GetString("SP03SaldoAwalBergerak", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to select f03_getbeginningbalance({0},{1}).
        '''</summary>
        Friend ReadOnly Property SP03SaldoAwalBerjalan() As String
            Get
                Return ResourceManager.GetString("SP03SaldoAwalBerjalan", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to select f04_getbeginningbalance({0},{1}).
        '''</summary>
        Friend ReadOnly Property SP04SaldoAwalBerjalan() As String
            Get
                Return ResourceManager.GetString("SP04SaldoAwalBerjalan", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to update {0} set {1}={2} where p_id={3}.
        '''</summary>
        Friend ReadOnly Property SQLUpdate1FieldWhereId() As String
            Get
                Return ResourceManager.GetString("SQLUpdate1FieldWhereId", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to update {0} set p_id={1} where p_id={2}.
        '''</summary>
        Friend ReadOnly Property SQLUpdateId() As String
            Get
                Return ResourceManager.GetString("SQLUpdateId", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to update {0} set primary_main={1} where primary_main={2}.
        '''</summary>
        Friend ReadOnly Property SQLUpdatePrimary() As String
            Get
                Return ResourceManager.GetString("SQLUpdatePrimary", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iufdihyiyg98y9gyr87y93443904309tu3984pyt03y0by37ytb85598ngyrubcg3uyctgreuycgewc.
        '''</summary>
        Friend ReadOnly Property VariableUserKey() As String
            Get
                Return ResourceManager.GetString("VariableUserKey", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
