'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EnnUqAu0P5BscBDJOaRNIQ==.
        '''</summary>
        Friend ReadOnly Property format1() As String
            Get
                Return ResourceManager.GetString("format1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to u5yXxOCjh5sSccCeN22yWmkrXvwllckG.
        '''</summary>
        Friend ReadOnly Property format2() As String
            Get
                Return ResourceManager.GetString("format2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mxq2LVJiPiU=.
        '''</summary>
        Friend ReadOnly Property format3() As String
            Get
                Return ResourceManager.GetString("format3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to bIPXbZTVxHaB4b0vO5SQNA==.
        '''</summary>
        Friend ReadOnly Property format4() As String
            Get
                Return ResourceManager.GetString("format4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to D4UwyEVQhLI=.
        '''</summary>
        Friend ReadOnly Property format5() As String
            Get
                Return ResourceManager.GetString("format5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to i08kAe4xtjM5RWuQoH3nLw==.
        '''</summary>
        Friend ReadOnly Property format6() As String
            Get
                Return ResourceManager.GetString("format6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to tBInn3aP3HjWE8CfcNEAmA==.
        '''</summary>
        Friend ReadOnly Property format7() As String
            Get
                Return ResourceManager.GetString("format7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property ssl() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("ssl", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to =-0987654321qwertyuiop[\&apos;;lkjhgfdsazxcvbnm,./.
        '''</summary>
        Friend ReadOnly Property VariableKey() As String
            Get
                Return ResourceManager.GetString("VariableKey", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
